name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install

      - name: Build bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
